[package]
name = "mmk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11 = "2.19.1"
x11rb = { version = "0.10.1", features = ["xkb"] }
